version: "3"
services:
  spring_boot_test_helm:
    # replace username/repo:tag with your name and image details
    #image: donekalvikram/testingdocker
    build: .
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet:
